package com.charlie.freedomroutes;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.LinkedList;
import java.util.Scanner;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


/**
 * Freedom Routes GUI for Windows
 * @author Charlie Jiang
 */
public class MainFrame extends javax.swing.JFrame {

    private LinkedList<String> datas = new LinkedList<>();
    private HttpURLConnection conn;
    private String rawWebData;
    private final LinkedList<String> webData = new LinkedList<>();
    private final ExecutorService exc = Executors.newCachedThreadPool();
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        File dataFile = new File("C:\\freedomroutesgui.txt");
        if(!dataFile.exists()){
            JOptionPane.showConfirmDialog(null, "数据不存在，将进行更新！", "提示", JOptionPane.INFORMATION_MESSAGE);
            exc.submit((Runnable) ()->{
                update();
            });
        }else{
            exc.submit((Runnable) ()->{
                try {
                    Scanner sc = new Scanner(new FileInputStream(dataFile));
                    while(sc.hasNext()){
                        datas.add(sc.nextLine());
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        proProgress = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        txtMetric = new javax.swing.JTextField();
        txtGateway = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Freedom Routes GUI for Windows");

        btnUpdate.setText("更新");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnStart.setText("启动");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("停止");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("警告：操作时请勿关闭程序！");

        jLabel2.setFont(new java.awt.Font("黑体", 2, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("作者：Charlie Jiang");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("路由距离（一般不修改）：");

        txtMetric.setText("5");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("国内网卡网关：");

        jLabel5.setFont(new java.awt.Font("楷体_GB2312", 0, 12)); // NOI18N
        jLabel5.setText("<html>\n<p>使用说明：请在本地连接（以太网）或宽带连接（视网络连接方式修改，计算机拨号则是宽带连接，路由器拨号则是本地连接或以太网）里面打开详细信息，将里面的默认网关或客户端IP地址填入网关输入框。尽量每月更新，填好数据之后点击“启动”。注意！重启之后需重新启动Freedom Routes GUI!</p>\n</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(proProgress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMetric, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGateway, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGateway, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMetric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStop)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(proProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        exc.submit((Runnable) ()->{
            update();
        });
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        exc.submit((Runnable) ()->{
            start();
        });
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        exc.submit((Runnable) ()->{
            stop();
        });
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    private void update(){
        try {
            SwingUtilities.invokeLater((Runnable) ()->{
                btnUpdate.setEnabled(false);
                btnStart.setEnabled(false);
                btnStop.setEnabled(false);
            });
            conn = (HttpURLConnection)(new URL("http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest").openConnection());
            InputStream input = conn.getInputStream();
            byte[] rawdata;
            byte[] temp = new byte[1024];
            int i;
            ByteArrayOutputStream tempread = new ByteArrayOutputStream();
            while((i = input.read(temp)) != -1){
                tempread.write(temp, 0, i);
            }
            rawdata = tempread.toByteArray();
            rawWebData = new String(rawdata);
            //System.out.println(rawWebData);
            Pattern pt = Pattern.compile("apnic\\|cn\\|ipv4\\|[0-9\\.]+\\|[0-9]+\\|[0-9]+\\|a.*",Pattern.CASE_INSENSITIVE);
            Matcher matcher = pt.matcher(rawWebData);
            while(matcher.find())
                webData.add(matcher.group());
            System.out.println(webData.getFirst());
            System.out.println(webData.getLast());
            for(String one:webData){
                String[] oneSp = one.split("\\|");
                //System.out.println(Arrays.toString(oneSp));
                String ip = oneSp[3];
                String num_ip = oneSp[4];
                int imask=0xffffffff^(Integer.parseInt(num_ip)-1);
                String imaskStr = Integer.toHexString(imask);
                int[] mask = {
                    Integer.parseInt(imaskStr.substring(0, 2),16),
                    Integer.parseInt(imaskStr.substring(2, 4),16),
                    Integer.parseInt(imaskStr.substring(4, 6),16),
                    Integer.parseInt(imaskStr.substring(6, 8),16),
                };
                String maskStr = 
                        Integer.toString(mask[0])+"."+
                        Integer.toString(mask[1])+"."+
                        Integer.toString(mask[2])+"."+
                        Integer.toString(mask[3]);
                datas.add(ip+"|"+maskStr);
                try (FileWriter fw = new FileWriter("C:\\freedomroutesgui.txt")) {
                    for(String data:datas)
                        fw.write(data+"\n");
                }
            }
            JOptionPane.showConfirmDialog(null, "操作完成！", "提示", JOptionPane.INFORMATION_MESSAGE);
            SwingUtilities.invokeLater((Runnable) ()->{
                btnUpdate.setEnabled(true);
                btnStart.setEnabled(true);
                btnStop.setEnabled(true);
            });
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "连接失败！", "错误", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } catch(StringIndexOutOfBoundsException ex){
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void start(){
        try {
            SwingUtilities.invokeLater((Runnable) ()->{
                btnUpdate.setEnabled(false);
                btnStart.setEnabled(false);
                btnStop.setEnabled(false);
                proProgress.setMaximum(datas.size());
                proProgress.setValue(0);
            });
            Runtime.getRuntime().exec("ipconfig /flushdns");

            for(String data:datas){
                String[] one = data.split("\\|");
                String cmd = "route add "+one[0]+" mask "+one[1]+" "+txtGateway.getText()+" metric "+ txtMetric.getText();
                Runtime.getRuntime().exec(cmd);
                SwingUtilities.invokeLater((Runnable) ()->{
                    proProgress.setValue(proProgress.getValue()+1);
                });
            }
            SwingUtilities.invokeLater((Runnable) ()->{
                btnUpdate.setEnabled(true);
                btnStart.setEnabled(true);
                btnStop.setEnabled(true);
            });
            JOptionPane.showConfirmDialog(null, "操作完成！", "提示", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void stop(){
        try {
            SwingUtilities.invokeLater((Runnable) ()->{
                btnUpdate.setEnabled(false);
                btnStart.setEnabled(false);
                btnStop.setEnabled(false);
                proProgress.setMaximum(datas.size());
                proProgress.setValue(0);
            });
            for(String data:datas){
                String[] one = data.split("\\|");
                Runtime.getRuntime().exec("route delete "+one[0]);
                SwingUtilities.invokeLater((Runnable) ()->{
                    proProgress.setValue(proProgress.getValue()+1);
                });
            }
            SwingUtilities.invokeLater((Runnable) ()->{
                btnUpdate.setEnabled(true);
                btnStart.setEnabled(true);
                btnStop.setEnabled(true);
            });
            JOptionPane.showConfirmDialog(null, "操作完成！", "提示", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar proProgress;
    private javax.swing.JTextField txtGateway;
    private javax.swing.JTextField txtMetric;
    // End of variables declaration//GEN-END:variables
}
